baseURL = "https://vari-sh.github.io/"
languageCode = "en-us"
theme = "anubis2"
title = "Vari-sh's Blog"

[params.author]
  name = "vari-sh"

[params]
  rssIcon = false

[[params.Social]]
  id = "github"
  url = "https://github.com/vari-sh"

[markup.goldmark.renderer]
  unsafe = true # true | false; Enable unsafe mode to have a better experience

[markup.highlight]
  style = 'base16-snazzy' # Chroma style, find more at here: https://swapoff.org/chroma/playground/


[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3


