baseURL = "https://vari-sh.github.io/"
languageCode = "en-us"
theme = "not-much"
title = "vari-sh's Blog"

[params]
theme = "dark"
palette = "catpuccin"
showThemeNotice = false
showPostsSummary = false 
[params.author]
  name = "vari-sh"

[markup]
  [markup.highlight]
    style = 'dracula'
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'

# Navigation
[menu]
  [[menu.main]]
    identifier = "home"
    name = "home"
    title = "Home"
    url = "/"
    weight = 1
  
  [[menu.main]]
    identifier = "posts"
    name = "posts"
    title = "posts"
    url = "/posts/"
    weight = 2
  
  [[menu.main]]
    identifier = "github"
    name = "github"
    title = "GitHub"
    url = "https://github.com/vari-sh"
    weight = 3


